// ebook_font_charset.h
// ==== 生成文件，请勿手改 —— 由 scripts/gen_font_charset.py 生成 ====
// 内置 puhui 字体（font_puhui_20_4.c）的字符集：6648 个码点。
// 编码：sorted 码点 -> delta -> LEB128 varint -> base64。
// 用途：阅读器 Web 上传页在浏览器端按此码点集裁剪用户字体（harfbuzzjs），
//       使裁后覆盖与设备内置字体一致。升级内置 puhui 后请重跑脚本。

#ifndef EBOOK_FONT_CHARSET_H
#define EBOOK_FONT_CHARSET_H

namespace ebook_font_charset {

// 码点集（delta-LEB128-base64）。前端 atob + varint 解码还原为码点数组。
inline const char* PuhuiB64() {
    return
        "CgMTAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
        "AQEBAQEBAQEBAQEBAQEBAQEBAQEBASIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEB"
        "AQEBAgIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgMBAgEBAgICAQEBAQICCAICAwEBAQsCAwEC"
        "AgIDAQECAgIFAQEBAwEBAQICBAICAgICBwEBAQEBEw8PHgICAkUCNgECBQIGCRQDAgcCBgInAQoBAQQECQECJAEBAQEEGwwyIwIC"
        "CAEBAQEBAQEBAQEBAQECAQECAQEBAQEBAwEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBMwIDAgIGAQEBAQEBAQEBAQEB"
        "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAgUwBAQIDAICCAUZ"
        "EJgSAQICAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQECAQEBAQEBAQEBAQEBAQYBAQEBAgEBAQEBAQEDAQEBAQHM"
        "IAICAgICAgICAgQEAgICAgICAgICAgICAgICAgICBAICAgICAgJ/ApEBBgIFAQIBAQECAQECAQECAQEEAQkCAQYBAQEINwQCASoN"
        "ShADDAQ6AQEuAQEBAQMBATkuAgECAQEBAwYBAwQBBAIDAgIBAQEBCQEBBgELGAEDASEBDgICDEo6AbYCAQEBAQEBDowBAQEaCAgk"
        "OAQGAQ0BCQgBAwYBCQEEAwEXHwE6AiMBBDZzYwFxAZcQAQEDAgEBAQEBAQEBAQEDAQEBBSYCAgICAQEBAQEBAQEBAQEBAQEBAQEB"
        "AQEBAQECAQEBAQEBAQEBAQEBAQIBAgECAQIBAgEBAQEBAQEBAQEBAQEBAQIDAQ4BAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEC"
        "AQECAQIBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIEAQIFAaUFtBGrIwECBAEBAQECAQIBAgEBAQIBAQEB"
        "AQEBAgECAQEBAQIBAgMCAgICAQEBAgEFAgMBAgEBAQEBAgEBAgEBAQQBAQEBBQoBAgsEBAIBAgECAQIBAgEDAgEDAQIBAgEBAQEB"
        "AgEBAQQDBQUBAQMBAQEDAQIBAQICAQEBAQEBCgEBBQICAgIEAQQCAgIJAwEBAQEGAQEBAwEBAQQCBAUBBAICAgIBBgMCBQEBAQEC"
        "AQEEAQEBAwEDBgMHAgcDBAECAgMCCgQCAwECAgEBAQYBBgoDAQEGBQEBBgEFAQEBAQcBBAEBAgcCBAgDAgICAgECBAEBBQIDAgMB"
        "AQINAgIFBAIDAgEGBQIJDwEBAQYCAQUIBAgJAQUEBgECAgQDBwgCBgUNDgQCBQQOBgcCCQgNAQECAQEBAQEBAgIDAQECBgIGAwIB"
        "AQIBAQECAQIBAQEBAQECAQEDBQEBAQEBAgEFAwICAgEEAgIBBwMBAgECAQEEAgMEAgIBAgEBAgIKAgMBAwIHAgEBAgMCAQEBAgIB"
        "AQIDAQMHAQUBAQEBAgMEAQMBAQEDAgYBAQEBAQYBAQQDAgEEAwIFCQECAgEFAwMKBAQBAQQECgIBAQEBAgUBAQEGAQEBBQUBAgIE"
        "AgIHAwMBBAEBAwIRAwIBAwEBBQECDQEBAgQDAQIHBAEKAQEDAQEBAgQBAQEEAQIBAQEBAQEBAgICAgEBAgIBBAQBAQIBAQIBAwIC"
        "AwIBAQMCAQkDAgUDAwECBQEECQQDAQUBAQEBAQEDAwIBAQECBAECAQEBAQIBAQEBAQEBAQEBAQMBAQEDAQQCAQICAQECAQEBAQEB"
        "AQICBAIBAQEBBQEBAQIBAQEBAgIBAQMBAgECAgIBAwICBgUCAQMBBgICAgkCAgMDAQEDBAIFAQIBAQICAQEDAQwBAQIBAQMCAgUF"
        "AwEDAgEBAQQBAwEFCAIEAQEBAQEDAQQIAgEJAQIGAQEDDAQDBQIBAQENBQECBAUEDAIDAQEBAwICAgYCBAICAgEBAwIBAQkEAgIB"
        "CgMCAgUCAQEEAggJBAEBAgQCBQIBAgICAgMIBgMFAQIBAwIJAQIBBA4CAgECAgUEDwUBAwUGBgEBAggCBgsHAQQQEQMFDgoGAQMC"
        "AgEBCQMBAQEBBgMBBQMCAwIFAQMCBwQEAQEEAwMHBAICBQMDAQEBAQYDAQIBAQEBAwICAgUICwEBBwcJBwEDBQMVCAMGCwEXAgEI"
        "AwEPDAMGBgEDARUCBQMDAQYLAgoJBQIOBAIDAgEJARgGCgICCQYHAQIBAQIBAwMEBwMCBAIGAQMBAgMBAgMCAgEBAgEBAgMDAQEB"
        "BAYDAQECAwECAwEBAQMGAgMCAwQFAQICAQQFAQECAQECAwUBAwMEAQYBAwEFBQYCAwgEAQUBAgEDAwIBBgIDBA8EAgIBAQEBDAUD"
        "AQMBBQQIAQICEAMMBQgEAQMKAQEBCBMIARcBCgQBBwMIAgsCAwMgAyQEAxkEAQIBAQECAQIDAQECAwIFBQMCAwQCAgIBAQIBAwYC"
        "AQEBAQEBAQEBAQEBAQIEAQMCAwEBAQIBBAEBAwIBAQEFBAIBCgEBAgQBAQEBAgEEBQECAQEBAQIBAgECAgEBAQEBAgEBAgMCAgID"
        "BwMFBQMDAQEBAgEBAQEBAQMBAgEBAQIBAQIECQIBAwEHAwIIBgIBDgEDAwMBBggEBAIFIQgEAQICAwMGBQwHBgIBBA4EEA8ECBFR"
        "CwgHCQEDAQMBAQEBAgMDAQEBAwQDAwEBAgECBAQFAQICAQEBCAEBBAIBAQEDAwEBBAEFAwcJDAEBCAcBAQICAQEBAQEBAQQBAgED"
        "BQEDAQECAgECAgEHAQQCCAEBAREBCQMEBQECARADAQMFAQEBAQEEAgEEAgICAgEDBAEFAQECBgIEAgIBAgoCBAIEAQIEBAUCAQED"
        "AQIBAwEGAgIBAwEBAwEDAgEBBAEBAQQBAQUDCAEEBQEBAgIEBgIBBgECAQEBBAEBAQMEAQYEBgQGAgIBAQEDCQQCAQEGAQMBBAIB"
        "AgUMAQcDBQIDAgMECQEBBAEBAgECAQMDBAIIAQQEBwIEBQEDAwICAgMDAgICBAkBBAEGBAMCAgMBAQUBAQECAQEBAQEBAgMDAQcH"
        "AQYGBQEEBAEDGAkDAQIDBAMKAQQBBgIFAQELCQMCAQMQAwEBAwYECAQGAQEIFA8BAQEEAwEIAgIBAQEBAQEEAgIBBAcEBAICAQEC"
        "AQEDAwEBAQYBAQICAQMBAQEEAwgEAgIBAQEBAQECAwMDAgEBBAUBBwEBAgEBAQIBAQICAgIBAwMBBQQEAwECAwMBAQEBAgEBAQIC"
        "AQECAQEBAQEBAwIBAQIBAQEBAwEBAQICAQMFAQEBAgEFAggFAwEBAgIBAQIBAQMCAQQLAwIDAwEDAgICAQUJAQIBAQQBBgQEAQMB"
        "BQIBBQEDAwECBAIBAgUBAQMCAQEBBgIFAw8EAgECBAQBBgIHAwEGCQMBAQMIAgEDAwYCDgEJBAcBAgIBAwgCBA8CDwEKBAkBAQMJ"
        "BgEEAgEBAQICBgQEAQEDAgMBAgEEAgYGBgYIBgQCEgIEBAEHAQoHAgECAwEGAwQDAgQBAQEBAgIBBAEDBgQCAgECAQ8EAQQBAgQC"
        "AgEDBQECAgMBAgEHAgMBBAQGAQMICQIDAQEBAQMBBAIDAQMGAgQBAwICAQQBAQQGAQUCAQUCAgQHAgMBAQYCAQMDAQEBAQEDBQUC"
        "AgYBAQQCBAQEAgMBCQUBCwUBAwMGEgMQAwEJBgQCAQEEAQMCAQEDBQECAgcBAgQCAgcCAgEBAQICAwEFAwMCAQMDBQEBAQUGAgEB"
        "AQQDBQIBAQQJAQIDBQcFAgMCAQUBBwECAgQDAQEMCwEBAQEBBgIEBQcDAgIBBwQBBAECAQMEAgIDAQoIAQ0BAQMBAQIBAQEDAgQE"
        "AQIBDQEBAgECAQ0JAgQOBAYFBAEBBQIBAwILBAUCAgUDAwIFAQMLAwQFCwgBBAoRAw8DCAkBBgQCDQgCAgMBBQICDgEHDAYGBwgI"
        "AgMIAwQeAgMICQYGAgIGAQcEBAsHDQEGAgoGDxAEDgoXOAkGFgEBAQQLCAQIAQIDAgIRAQEBAQEBAgEFAwEBAwEBAgEHAwECAQEL"
        "AgkTAQIDAgMBAQEDBgIBAQMBAQECAgIGCgQgAgIBAwQEAwEEAQYBAQQECAEBBQIHBQIEAgEBAQEDBgYCAgIDAQMBAwEBAgMBAwQC"
        "AQMDAgQCAQMBAQMBAwUFAQIBAQEBAgMFAQIHAgIEBQEBAQIDAgUBAwIDAwEBAQMKBwUEAwcFBwEDBgEBAQMEAQEDAQMBAgEBBgEC"
        "BwMDAQQGAwEKAwMBAwIFAgYCAgICAQIBAQEGAwMHBAQBAQEEAQUHAgcDBAECAQIDAgICAgEBAQkDAgMBAgQDAwECAwECAQUDAQID"
        "AgQCBAUHAwkCAwwHAQ8BAQMCBAcGBgECAwMFAQQFAgQLAgQGAwEFBAMDAQMBCwoBAgEEAwYEAQELAgcBAQYBAQUGAQgGBwQDAQYC"
        "CQECCgIIBAYOBQMPBgcDDwMKAgMKEBECCQEjDgUSCAICAQUBAgQBAQEKAQQEAgEBAwMPAQEBAQQFAQECAQQBAQUHCQECBAUCAQED"
        "AQECCAIEDAELAQMBBwUJAQEFBg0DAgsDAgYCAQIFBAsHBgUFBQYBCAQFBAQKBQYEAwoGIQoLDwIBBAEDAQEBAQEBAgEIAQEEDQIE"
        "AQEBBQIJAwQBAwMBCSIDBwMHAgIECAcCBQIBCAMBAQIBBwQSBwEFAQEIBAEBAwYCCAEFAQkaCgMDAwkDAgILBQoEAgMBAQIIAQUC"
        "CAMCAg0CCQQRBQIBAwcLBwMBBAYDAQEBBhkEAQEBAgEFBgYGCAIDBAQFDgEIAQgsBgEDCAgBDRQCAgMDAQIDAQIBBAEBAQICAQIB"
        "CgcDBQUDBgMFAQUEAgIOBAUCBgIBAwICAwcDAQIBAwMBAwEBBAMCAQEBCAIBAwMDBAEHAQUEBQYBCw0BBgEEAgMBARMECgoGBwgN"
        "AgEBAQEEAgIBBAMFAwMVAwkFAwQCAgQBAQEBAgIBAQMBAwICAQMHAQMCBAQCAwcBAgESAQEIAQYHAQECAgICAQ8BCgEFAgMFAQ0F"
        "AQUBCQQNBgICAQIBAwMIBBgEAQYBAgQCAgEFAwgBAgEKAQcCBAsLBAMBAgQCBQ0DCA4BAg4QAQEDBgEHCAIHAQIHAgIDBAUBBQUF"
        "Dg8DBw0LDQ4GAgICAQEGAQcGBQIBAQEFAwUCCAECBgEDAQgCFwEDBAsBAQIBAgECAwMCAgQBBgcFAgECBgEIAwIDBQYCAQwGAwsD"
        "AgQEAQECAQYHAQkSAgkCAQIBBQICAQkEAQQBAQQBAgYBAwURDAsDBQEBAwIIAgcDAQUECAYDBQIFBgIEDgIKAwIEAQEBAgIFAgMR"
        "BAICBQINBwECCgoCBA8EAgECGA0DBhAaBgMOBQICAgkBExMIAgwIAQMCAQcFAQUEAwIGAwEBDAsBAwMDAQcIDAMCBAEFAQIDBAMC"
        "AQEFAgUEAwEBCQkCCAQFDAUIAwEDAQsSBgECBAsCBAENCwUDCAkFAQsHKAgDAwwBAxMKCwEBBQMJBgoDBQIKAgEBAgEDAgMCAQEC"
        "AQEBAQEDAgQBAQEBAQIDAQECAQECAwEBAQEBAQEDAQICAgEBAgEBAQMBAQIBBAEBAQEFAQIBBQUBAQECAgMDBAQBAQMBBgQCFgEE"
        "AgMHAQcBBAICAwICCAQFAgIGBgQBAgIBAwEBBgMHBAICBAUCAgQCBAcBAQgHAQoBBAECAgcBAwUCAQENDQMCAwICAwQEAQEIAgIC"
        "BAwFAQIFBgIEAgEBAgIBCgICAQIDAQECAQQBBAECAQIGAwEBAQECAwYCCAQCAgMDAQIEAgIBAQIDAgIDBQMBAgEBBQEBAgMCAhEE"
        "AgIFAQUMAQECAgECAQEQAQUDAgECBQEBAQMBAQgCBQsBAQEDCAEKBwMDAgQDCgwEAgIBAgMGAQYBAQkBAQEBAQIBBQIIAgELAgQB"
        "BAEDDhEOCAEBAQEBBwQECAECAQQHAwEIAQMBAgEBAQICBAEBBAoGAgIBAQEDBAMBBgEJAgYCCAEBAQEEBQkFCwEDAQMCAQMBAgEH"
        "BgMHAgIGBQICAQMEBAgFCQEDAQQFBQYNBgEFAgEDBAYDAhAECQYCAREBBgIBAQ8HAQEBAQQFBwQBCQMOBAYCBgIBBQQNCQ4DFgYE"
        "AwIDBQIICgkGAiMCBAMHAgkJAgMBAQEGBgEPEAQHCgYDCAIKCwMBAgMBGQQCBggHAQQSDAMBBhwLBw8BAQEDAQUBAwEIBA4EAQIB"
        "AQgCBwIIIwcDAQ4CBAUKAg4CAhABAgIBBAUEEgQECAIFBwICBwYOAgwBChsSDAwOEgcFFw0ZBQUBBgEGAQMCAgIEAQECAwMBBAcK"
        "AwEGAgkGDwIEEAEDCgUBAwEDAQQDDwEEAQQFBQkCCAsFCAQOGxMNAgIDBQQHBA0DCQcDAwEBAgEBAgEIAREDEggCBgIEBQQBBQIE"
        "BwMEAgEGAQEUBQkEBAMEBAEBBg4CAwEGAgMGAgQGAgEDAg0IBAsREAEGAgIXAgIcEA8ECgYDAQcGAwoJBwcBAgEDAQEDAQEBAgED"
        "AQEBAQIBAQEBAQIBAQECAQEDAgIEAgMBAgECAQEBAgEBBAEBAgIBAgEBAQECAQIBAwICAwIBAgEBAQIBAgQBAQEDAwEBAgEBBAEE"
        "AwMKBQICAgQKBwkBAQ0JCgcKAQIBAQUBAQEBAQgDAQMBAwEHAQIJCQICAgEDBAIBBwYCAQsCBQ4BAQIBAQEBAQEBAQEBAQEBAQEB"
        "AwECAQEBAQECAQIBAQEEAwECAQEEAgICAQMCAQEBAQIFBQQBAQEKBAUBCgQGBAULAQoFAQcBBQwCAgMEAgUEAgIDAQ4BBQENAQQH"
        "AQcEBAsEAg8LAgYBBQ8MHgEDAwgGCgIBBQ0DFgUGBgsBBgIMAQUJERYHAQEBAwIBAQQCBQEBAgQBAQECAQEDAwECAgEBAgIBAgEE"
        "AwIBAgICAQEBBwECAQEDAQIBAgEGAgEDBAECAQEBAQMDAQQBAgMEAwEBBAMBAQECAQMBAwIBAgIDAgEBAgEBAQIBCwMBBgMBAgMB"
        "BQMBAgEBAQMBAQICAgMCAwIEBAEEAgECAQIFAQEBAQEGBQICDwEDBAQBAgQDAQIGCQQDDAQHBQgDBQUHEA4GAxkCAQEDAggDBgIF"
        "AgIBAQEEAQEBBwgCAgcIARABGwIBAQEBAQECCwEGURAXGQwFExsEGxgSCB4EBQQDGAEQGgkYGBoZNx0PDRoSCwEBCQQCAgIBAQEC"
        "AwEBAQEFAgECAQEGAwIBAQECCQ0BAQMDCQEBAgIDAQICBAEBAQECAQMDAQQJAQcBAQEBAQcBAQEFBgUBAQUGBAUGEwEGAQgBAwYC"
        "BgEBDwECDAEUBAwGDAIBAgEBAQICAQIBAQEBAgMBBAMGAgEDAgMDAwsEAwEBAQEBBQQBAgIBAQEBAwEBAwUGBgEBAQQBAQYDAgEB"
        "AQIDCAEEAQMBAQQEAQIBCwECBwUFAgECAQMBAQEFAQICBAEDAwIEAQUCBQMBAwECAgMCAQMCAQIEAQEEAwYCCQsGAQUKCgEDAwMC"
        "AgEBBwoBAhUCCwgNHggTAQIDAQYCAQUEAgEBAgECCAECBAEVCwMBCgYBAgUEBgkEBAYBAQIBAQIBAQIBAgEBAQECAgQBAgECAQEE"
        "AQMEBBwKBAYBAgMBEAMKAQEHBQYDBRAqEwUDAQIBAQMBAQMCAwEFAQIDAgIDBAMMAwQCEwQLBQYzBQYXFRACAwUNAQIBAQIBAgMC"
        "AQIBAgECAgEEAQMCBgMKAQMOAQEECQYIAQQBDQgNCw0MBgIKCwUBAgEKBQYVP84BBQwPCAQDBwYMCAEJAQcHDgEyAhMxSEUmAQEB"
        "AQIBBwIECgEBBAIEAQUVAgcDDQITAQQGAgYBDwYBAQEFAQoBAgECBAMCAQoHHwUNGw8GAg8BHQUEBQMJAQID4RgBAwQIAgMBAwMB"
        "UwQECAMJFAgBAwQNBxwBEgIHBBE/HAEDHFAEGAEDBAgBJwgIDIwB7AIZOwQECAQIVAgIDBwEDCgEEQVyBIgBBAQNIxAMBAQIAQQH"
        "VAQYCEwBBw0/BAQIASdUJBQBAwMBDSMcHFgXVasCQQEDDAUHBAwNFCMEDAEKARwBAwQNBxwBA2wccAgIDAQECCgBAwwBBAcBAwIC"
        "DQEGVAEbHAQRAiEBEnkEBIQBOAQEDwUBAwMBDQcBUwQMAQsgBA0jAQMEhAEBAwSEAQgwHMwEBAQCBgEEBwEUPwEDBA0HBBw0AQMR"
        "dwQEC1InEQQjAQMECAEJcogDOBwBAwICCAQBBQIBGwEUIwEDAwEJAQEBCBwBAwQIBAEHHAQEFAQRIxwVBwQECAwEBDAcAQcUBAQI"
        "BQccAQMEAQcBAwgBBwkEBxU/AQMECAEEBwEbFCQBAxEGcQEDBA13AQ8FIwEDBAkEBxzFAesCAQcIBQEGAVMEBAsCBxw4FT84AQcN"
        "PzgBFCMBAwQIDCBQEAwcOJgCBAQwHAQECAwBUwQYEEQVd4wBATcVBwQPCVQcIBEjcCxgHAgwCBQBAwQIAQICBxQBHCMQLAQJBCMc"
        "AQMEDSMBGxyoARz4RgEBAa0GIBOcAQIBAwECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQgBAQEDAQcCAgIEBAQBAQUIAgeA"
        "ARg=";
}

// 码点总数（供前端/日志核对）。
inline int PuhuiCount() { return 6648; }

}  // namespace ebook_font_charset

#endif  // EBOOK_FONT_CHARSET_H
