// ebook_web_page.h
// 书籍/字体管理网页（内联 HTML/CSS/JS 单常量）。上传/删除 /sdcard/books 下的
// .txt / .epub 书籍与 .ttf / .otf 阅读字体（列表按 type 分「书架」「字体」两组）。
// 上传用 XHR 把文件原始字节 POST 到 /api/upload?name=，带进度。Claude.ai 风深色主题。

#ifndef EBOOK_WEB_PAGE_H
#define EBOOK_WEB_PAGE_H

namespace ebook_web_page {

inline const char* Html() {
    return
        "<!DOCTYPE html><html lang='zh'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>书籍管理</title><style>"
        "*{box-sizing:border-box}"
        "body{margin:0;padding:20px;font-family:-apple-system,system-ui,sans-serif;"
        "background:#0e1116;color:#e6e6e6;max-width:640px;margin:0 auto}"
        "h1{font-size:22px;margin:8px 0}"
        ".sub{color:#8b93a1;font-size:13px;margin:4px 0 16px}"
        ".card{background:#161b22;border:1px solid #263041;border-radius:12px;"
        "padding:16px;margin-bottom:16px}"
        ".drop{border:2px dashed #2f4058;border-radius:12px;padding:26px 16px;text-align:center;"
        "color:#8b93a1;font-size:14px;cursor:pointer}"
        ".drop.hot{border-color:#2f6f52;color:#cfe;background:#111b16}"
        "ul{list-style:none;margin:0;padding:0}"
        "li{display:flex;align-items:center;gap:10px;padding:11px 0;"
        "border-bottom:1px solid #21262d}li:last-child{border-bottom:0}"
        ".meta{flex:1;min-width:0}"
        ".name{font-size:15px;word-break:break-all}"
        ".sz{color:#8b93a1;font-size:12px;margin-top:2px}"
        "button{background:#263041;color:#e6e6e6;border:0;border-radius:8px;"
        "padding:8px 14px;font-size:14px;cursor:pointer}"
        "button.del{color:#ff6b6b}button:disabled{opacity:.4}"
        ".prog{height:6px;background:#0e1116;border-radius:4px;overflow:hidden;margin-top:10px;display:none}"
        ".prog.on{display:block}.bar{height:100%;width:0;background:#2f6f52;transition:.1s}"
        ".pf{font-size:12px;color:#8b93a1;margin-top:6px;min-height:16px}"
        ".empty{color:#8b93a1;padding:12px 0}"
        ".toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);"
        "background:#2f6f52;color:#fff;padding:10px 18px;border-radius:20px;"
        "opacity:0;transition:.2s;pointer-events:none;max-width:80%}"
        ".toast.show{opacity:1}.toast.err{background:#a33}"
        "</style></head><body>"
        "<h1>书籍 / 字体管理</h1>"
        "<p class='sub'>上传 / 删除 SD 卡里的 TXT / EPUB 书籍，以及 TTF / OTF 阅读字体。"
        "上传后在设备上返回书架 / 阅读菜单即可看到。</p>"
        "<div class='card'>"
        "<div id='drop' class='drop'>点此选择 .txt / .epub / .ttf / .otf 文件，或拖拽到这里上传<br>（可多选）</div>"
        "<input id='fi' type='file' accept='.txt,.epub,.ttf,.otf' multiple style='display:none'>"
        "<div id='prog' class='prog'><div id='bar' class='bar'></div></div>"
        "<div id='pf' class='pf'></div>"
        "</div>"
        "<div class='card'><h2 style='font-size:16px;margin:0 0 10px'>书架</h2>"
        "<ul id='list'></ul><div id='empty' class='empty' style='display:none'>暂无书籍</div></div>"
        "<div class='card'><h2 style='font-size:16px;margin:0 0 10px'>字体</h2>"
        "<ul id='flist'></ul><div id='fempty' class='empty' style='display:none'>暂无字体</div></div>"
        "<div id='toast' class='toast'></div>"
        "<script>"
        "var listEl=document.getElementById('list'),emptyEl=document.getElementById('empty');"
        "var flistEl=document.getElementById('flist'),femptyEl=document.getElementById('fempty');"
        "var fi=document.getElementById('fi'),drop=document.getElementById('drop');"
        "var prog=document.getElementById('prog'),bar=document.getElementById('bar'),pf=document.getElementById('pf');"
        "function toast(m,e){var t=document.getElementById('toast');t.textContent=m;"
        "t.className='toast show'+(e?' err':'');setTimeout(function(){t.className='toast'+(e?' err':'')},2200);}"
        "function fmt(n){if(n>=1048576)return(n/1048576).toFixed(2)+' MB';"
        "if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B';}"
        "function row(b,ul){var li=document.createElement('li');"
        "var m=document.createElement('div');m.className='meta';"
        "var nm=document.createElement('div');nm.className='name';nm.textContent=b.name;"
        "var sz=document.createElement('div');sz.className='sz';sz.textContent=fmt(b.size);"
        "m.appendChild(nm);m.appendChild(sz);"
        "var db=document.createElement('button');db.className='del';db.textContent='删除';"
        "db.onclick=function(){del(b.name)};"
        "li.appendChild(m);li.appendChild(db);ul.appendChild(li);}"
        "function load(){fetch('/api/list').then(function(r){return r.json()}).then(function(a){"
        "listEl.innerHTML='';flistEl.innerHTML='';var nb=0,nf=0;"
        "a.forEach(function(b){if(b.type==='font'){nf++;row(b,flistEl);}else{nb++;row(b,listEl);}});"
        "emptyEl.style.display=nb?'none':'block';femptyEl.style.display=nf?'none':'block';"
        "}).catch(function(){toast('读取列表失败',1)});}"
        "function del(name){if(!confirm('删除 '+name+' ？'))return;"
        "fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},"
        "body:'name='+encodeURIComponent(name)}).then(function(r){"
        "if(r.status===200){toast('已删除');load();}else{r.text().then(function(t){toast(t||'删除失败',1)});}"
        "}).catch(function(){toast('删除失败',1)});}"
        // ---- 字体裁剪：上传前在浏览器按内置 puhui 字符集裁字体（harfbuzzjs subset wasm，走 CDN）。
        //      裁不了（离线/CDN 失败/裁剪异常）时回退到 5MB 上限，超过即拒收。----
        "var CDN_WASM='https://cdn.jsdelivr.net/npm/harfbuzzjs@1.4.0/dist/harfbuzz-subset.wasm';"
        "var MAX_NOSUB=5*1048576;var FONT_RE=/\\.(ttf|otf)$/i;var hbP=null;"
        // base64(delta-LEB128) -> 码点数组（对应 scripts/gen_font_charset.py 的编码）
        "function decodeCS(b64){var s=atob(b64),c=[],p=0,v=0,sh=0;for(var i=0;i<s.length;i++){"
        "var b=s.charCodeAt(i);v|=(b&0x7f)<<sh;if(b&0x80){sh+=7;}else{p+=v;c.push(p);v=0;sh=0;}}return c;}"
        // 懒加载 subset wasm + 字符集，缓存 Promise（离线首次失败后后续快速回退）
        "function ensureSub(){if(hbP)return hbP;hbP=Promise.all(["
        "fetch(CDN_WASM).then(function(r){if(!r.ok)throw 0;return r.arrayBuffer()}).then(function(b){return WebAssembly.instantiate(b,{})}),"
        "fetch('/api/font-charset').then(function(r){if(!r.ok)throw 0;return r.text()})"
        "]).then(function(a){return{e:a[0].instance.exports,cps:decodeCS(a[1])};});return hbP;}"
        // 低层 hb_subset_* C API：内存模式 WRITABLE(2) + 显式 free，避免整包再复制
        "function hbSubset(e,fb,cps){var u8=function(){return new Uint8Array(e.memory.buffer)};"
        "var fp=e.malloc(fb.length);u8().set(fb,fp);"
        "var bl=e.hb_blob_create(fp,fb.length,2,0,0);var fc=e.hb_face_create(bl,0);e.hb_blob_destroy(bl);"
        "var inp=e.hb_subset_input_create_or_fail();if(!inp){e.hb_face_destroy(fc);e.free(fp);throw new Error('subset input');}"
        "var us=e.hb_subset_input_unicode_set(inp);for(var i=0;i<cps.length;i++)e.hb_set_add(us,cps[i]);"
        "var sf=e.hb_subset_or_fail(fc,inp);e.hb_subset_input_destroy(inp);e.hb_face_destroy(fc);e.free(fp);"
        "if(!sf)throw new Error('subset fail');"
        "var rb=e.hb_face_reference_blob(sf);var dp=e.hb_blob_get_data(rb,0);var ln=e.hb_blob_get_length(rb);"
        "var out=u8().slice(dp,dp+ln);e.hb_blob_destroy(rb);e.hb_face_destroy(sf);return out;}"
        // up(name,payload,cb)：payload 可为 File 或 Blob，name 独立传（裁后仍用原文件名）
        "function up(name,payload,cb){var xhr=new XMLHttpRequest();"
        "xhr.open('POST','/api/upload?name='+encodeURIComponent(name));"
        "xhr.upload.onprogress=function(e){if(e.lengthComputable){bar.style.width=(e.loaded/e.total*100)+'%';}};"
        "xhr.onload=function(){cb(xhr.status===200,xhr.responseText)};"
        "xhr.onerror=function(){cb(false,'网络错误')};xhr.send(payload);}"
        "function upAll(files){var arr=[];for(var i=0;i<files.length;i++){"
        "var f=files[i];if(/\\.(txt|epub|ttf|otf)$/i.test(f.name))arr.push(f);}"
        "if(!arr.length){toast('请选择 .txt / .epub / .ttf / .otf 文件',1);return;}"
        "prog.className='prog on';var idx=0;"
        "function fin(){prog.className='prog';bar.style.width='0';pf.textContent='';toast('上传完成');load();}"
        "function adv(){idx++;next();}"
        "function send(name,payload,tag){pf.textContent='上传中 ('+(idx+1)+'/'+arr.length+')：'+name+(tag||'');bar.style.width='0';"
        "up(name,payload,function(ok,msg){if(!ok)toast(name+'：'+(msg||'失败'),1);adv();});}"
        "function next(){if(idx>=arr.length){fin();return;}var f=arr[idx];"
        "if(!FONT_RE.test(f.name)){send(f.name,f,'');return;}"
        "pf.textContent='准备字体 ('+(idx+1)+'/'+arr.length+')：'+f.name;bar.style.width='0';"
        "ensureSub().then(function(hb){pf.textContent='裁剪中：'+f.name+'…';"
        "return f.arrayBuffer().then(function(buf){var inb=new Uint8Array(buf);var out=hbSubset(hb.e,inb,hb.cps);"
        "toast('已裁剪 '+fmt(inb.length)+' → '+fmt(out.length));"
        "send(f.name,new Blob([out]),'（已裁剪 '+fmt(inb.length)+'→'+fmt(out.length)+'）');});"
        "}).catch(function(){if(f.size<=MAX_NOSUB){send(f.name,f,'（未裁剪）');}"
        "else{toast(f.name+'：'+fmt(f.size)+' 超过 5MB 且无法在浏览器裁剪，请联网后重试或换更小字体',1);adv();}});}"
        "next();}"
        "drop.onclick=function(){fi.click()};"
        "fi.onchange=function(){if(fi.files.length)upAll(fi.files);fi.value='';};"
        "drop.ondragover=function(e){e.preventDefault();drop.className='drop hot'};"
        "drop.ondragleave=function(){drop.className='drop'};"
        "drop.ondrop=function(e){e.preventDefault();drop.className='drop';if(e.dataTransfer.files.length)upAll(e.dataTransfer.files);};"
        "load();"
        "</script></body></html>";
}

}  // namespace ebook_web_page

#endif  // EBOOK_WEB_PAGE_H
