// stock_web_page.h
// 自选股 Web 配置页（内联 HTML/CSS/JS，单文件常量）。Claude.ai 风格深色主题。

#ifndef STOCK_WEB_PAGE_H
#define STOCK_WEB_PAGE_H

namespace stock_web_page {

inline const char* Html() {
    return
        "<!DOCTYPE html><html lang=\"zh\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>自选股配置</title><style>"
        "*{box-sizing:border-box}"
        "body{margin:0;padding:20px;font-family:-apple-system,system-ui,sans-serif;"
        "background:#0e1116;color:#e6e6e6;max-width:640px;margin:0 auto}"
        "h1{font-size:22px;margin:8px 0}h2{font-size:16px;margin:0 0 12px}"
        ".sub{color:#8b93a1;font-size:13px;margin:4px 0 16px}"
        ".card{background:#161b22;border:1px solid #263041;border-radius:12px;"
        "padding:16px;margin-bottom:16px}"
        "ul{list-style:none;margin:0;padding:0}"
        "li{display:flex;align-items:center;gap:10px;padding:10px 0;"
        "border-bottom:1px solid #21262d}li:last-child{border-bottom:0}"
        ".meta{flex:1;min-width:0}.name{font-size:15px}"
        ".sym{color:#8b93a1;font-size:12px}"
        "button{background:#263041;color:#e6e6e6;border:0;border-radius:8px;"
        "padding:8px 12px;font-size:14px;cursor:pointer}"
        "button.add{background:#2f6f52}button:disabled{opacity:.4}"
        "button.del{color:#ff6b6b}"
        "input{width:100%;background:#0e1116;color:#e6e6e6;border:1px solid #263041;"
        "border-radius:8px;padding:10px;font-size:15px}"
        ".name-edit{width:auto;flex:1}"
        ".empty{color:#8b93a1;padding:12px 0}"
        ".toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);"
        "background:#2f6f52;color:#fff;padding:10px 18px;border-radius:20px;"
        "opacity:0;transition:.2s;pointer-events:none}.toast.show{opacity:1}"
        "</style></head><body>"
        "<h1>自选股配置</h1>"
        "<p class=\"sub\">编辑后在设备上点返回列表即可生效。symbol 用腾讯格式："
        "sh600519 / hk00700 / usAAPL.OQ</p>"
        "<div class=\"card\"><h2>当前列表 <span id=\"cnt\"></span></h2>"
        "<ul id=\"list\"></ul></div>"
        "<div class=\"card\"><h2>添加</h2>"
        "<input id=\"q\" type=\"search\" autocomplete=\"off\" "
        "placeholder=\"名称 / 代码 / 拼音（茅台 600519 tencent aapl）\">"
        "<ul id=\"res\"></ul></div>"
        "<div id=\"toast\" class=\"toast\"></div>"
        "<script>"
        "const $=id=>document.getElementById(id);"
        "const esc=s=>s.replace(/[<>&\"]/g,c=>({\"<\":\"&lt;\",\">\":\"&gt;\",\"&\":\"&amp;\",'\"':\"&quot;\"}[c]));"
        "function toast(t){const e=$(\"toast\");e.textContent=t;e.classList.add(\"show\");"
        "setTimeout(()=>e.classList.remove(\"show\"),1500)}"
        "let curList=[];"
        "async function refreshList(){"
        "const r=await fetch('/api/list').then(r=>r.json());curList=r;"
        "$(\"cnt\").textContent='('+r.length+'/16)';"
        "$(\"list\").innerHTML=r.length?r.map((s,i)=>"
        "`<li><div class=\"meta\"><div class=\"name\">${esc(s.name)}</div>"
        "<div class=\"sym\">${esc(s.symbol)}</div></div>"
        "<button class=\"edit\" data-sym=\"${esc(s.symbol)}\" data-name=\"${esc(s.name)}\">✎</button>"
        "<button class=\"move\" data-idx=\"${i}\" data-dir=\"up\" ${i===0?'disabled':''}>↑</button>"
        "<button class=\"move\" data-idx=\"${i}\" data-dir=\"down\" ${i===r.length-1?'disabled':''}>↓</button>"
        "<button class=\"del\" data-sym=\"${esc(s.symbol)}\">×</button></li>`).join('')"
        ":'<div class=\"empty\">还没有自选股</div>'}"
        "async function search(q){"
        "if(!q.trim()){$(\"res\").innerHTML='';return}"
        "const r=await fetch('/api/search?q='+encodeURIComponent(q)).then(r=>r.json());"
        "$(\"res\").innerHTML=r.length?r.map(s=>"
        "`<li><div class=\"meta\"><div class=\"name\">${esc(s.name)}</div>"
        "<div class=\"sym\">${esc(s.symbol)}</div></div>"
        "<button class=\"add\" data-sym=\"${esc(s.symbol)}\" data-name=\"${esc(s.name)}\">添加</button></li>`).join('')"
        ":'<div class=\"empty\">无匹配</div>'}"
        "async function add(sym,name){"
        "const f=new URLSearchParams();f.append('symbol',sym);f.append('name',name);"
        "const r=await fetch('/api/add',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f});"
        "if(r.ok){toast('已添加 '+name);refreshList();$(\"q\").value='';$(\"res\").innerHTML=''}"
        "else{toast(await r.text()||'添加失败')}}"
        "async function del(sym){if(!confirm('删除 '+sym+'?'))return;"
        "const f=new URLSearchParams();f.append('symbol',sym);"
        "await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f});"
        "toast('已删除');refreshList()}"
        "async function move(i,dir){const j=dir==='up'?i-1:i+1;"
        "if(j<0||j>=curList.length)return;"
        "const a=curList.slice();const t=a[i];a[i]=a[j];a[j]=t;"
        "const f=new URLSearchParams();f.append('symbols',a.map(s=>s.symbol).join(','));"
        "const r=await fetch('/api/reorder',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f});"
        "if(r.ok){curList=a;refreshList()}else{toast(await r.text()||'排序失败')}}"
        "function startRename(li,sym,oldName){"
        "const meta=li.querySelector('.meta');const nameDiv=meta&&meta.querySelector('.name');"
        "if(!nameDiv||meta.querySelector('.name-edit'))return;"
        "const inp=document.createElement('input');"
        "inp.className='name-edit';inp.value=oldName;inp.maxLength=31;"
        "nameDiv.replaceWith(inp);inp.focus();inp.select();let done=false;"
        "const finish=async commit=>{if(done)return;done=true;"
        "const v=inp.value.trim();if(!commit||!v||v===oldName){refreshList();return}"
        "const f=new URLSearchParams();f.append('symbol',sym);f.append('name',v);"
        "const r=await fetch('/api/rename',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f});"
        "if(r.ok)toast('已改名');else toast(await r.text()||'改名失败');refreshList()};"
        "inp.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();finish(true)}"
        "else if(e.key==='Escape'){e.preventDefault();finish(false)}});"
        "inp.addEventListener('blur',()=>finish(true))}"
        "$(\"res\").addEventListener('click',e=>{const b=e.target.closest('button.add');"
        "if(b)add(b.dataset.sym,b.dataset.name)});"
        "$(\"list\").addEventListener('click',e=>{"
        "const d=e.target.closest('button.del');if(d){del(d.dataset.sym);return}"
        "const ed=e.target.closest('button.edit');"
        "if(ed){startRename(ed.closest('li'),ed.dataset.sym,ed.dataset.name);return}"
        "const m=e.target.closest('button.move');"
        "if(m&&!m.disabled)move(+m.dataset.idx,m.dataset.dir)});"
        "let t;$(\"q\").addEventListener('input',e=>{clearTimeout(t);t=setTimeout(()=>search(e.target.value),300)});"
        "refreshList();"
        "</script></body></html>";
}

}  // namespace stock_web_page

#endif  // STOCK_WEB_PAGE_H
