// Auto-generated by scripts/gen_weather_city_list.py -- DO NOT EDIT BY HAND.
//
// 数据来源：weather_district_id.csv（省 / 市 / 区县三级联动）。
// kProvinces -> kCities -> kDistricts，各级通过 start/count 索引连续区间。

#pragma once

#include <stddef.h>
#include <stdint.h>

namespace weather_cities {

struct DistrictEntry {
    const char* name;  // 区县名，例如 "海淀"
    const char* id;    // district_id，例如 "110108"
};

struct CityEntry {
    const char* name;           // 城市名，例如 "北京市"
    uint16_t district_start;    // 在 kDistricts 中的起始下标
    uint16_t district_count;    // 该城市下区县数量
};

struct ProvinceEntry {
    const char* name;       // 省/直辖市/自治区名
    uint16_t city_start;    // 在 kCities 中的起始下标
    uint16_t city_count;    // 该省下城市数量
};

extern const ProvinceEntry kProvinces[];
extern const size_t kProvinceCount;

extern const CityEntry kCities[];
extern const size_t kCityCount;

extern const DistrictEntry kDistricts[];
extern const size_t kDistrictCount;

struct LookupResult {
    size_t province_idx;
    size_t city_idx;
    size_t district_idx;
};

LookupResult FindDistrictById(const char* district_id);

const DistrictEntry* GetDistrict(size_t province_idx, size_t city_idx,
                                 size_t district_idx);

}  // namespace weather_cities
