#!/usr/bin/env python3
"""Generate province / city / district tables for the weather screen.

Input: weather_district_id.csv with columns:
  district_id, province, city, city_geocode, district, district_geocode, lon, lat

Output:
  main/display/screen/weather_screen/weather_city_list.h
  main/display/screen/weather_screen/weather_city_list.cc

Usage (from repo root):
  python3 scripts/gen_weather_city_list.py scripts/data/weather_district_id.csv
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "main" / "display" / "screen" / "weather_screen"

HEADER = """\
// Auto-generated by scripts/gen_weather_city_list.py -- DO NOT EDIT BY HAND.
//
// 数据来源：weather_district_id.csv（省 / 市 / 区县三级联动）。
// kProvinces -> kCities -> kDistricts，各级通过 start/count 索引连续区间。
"""


def parse_district_csv(csv_path: Path):
    """Return nested dict province -> city -> list of (district_name, district_id)."""
    nested: dict[str, dict[str, list[tuple[str, str]]]] = defaultdict(
        lambda: defaultdict(list)
    )
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            district_id = row.get("district_id", "").strip()
            province = row.get("province", "").strip()
            city = row.get("city", "").strip()
            district = row.get("district", "").strip()
            if not district_id or not province or not city or not district:
                continue
            nested[province][city].append((district, district_id))

    for prov in nested:
        for city in nested[prov]:
            nested[prov][city].sort(key=lambda x: (x[1], x[0]))
    return nested


def cpp_string_literal(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_header():
    h = OUT_DIR / "weather_city_list.h"
    h.write_text(
        HEADER
        + """
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace weather_cities {

struct DistrictEntry {
    const char* name;  // 区县名，例如 "海淀"
    const char* id;    // district_id，例如 "110108"
};

struct CityEntry {
    const char* name;           // 城市名，例如 "北京市"
    uint16_t district_start;    // 在 kDistricts 中的起始下标
    uint16_t district_count;    // 该城市下区县数量
};

struct ProvinceEntry {
    const char* name;       // 省/直辖市/自治区名
    uint16_t city_start;    // 在 kCities 中的起始下标
    uint16_t city_count;    // 该省下城市数量
};

extern const ProvinceEntry kProvinces[];
extern const size_t kProvinceCount;

extern const CityEntry kCities[];
extern const size_t kCityCount;

extern const DistrictEntry kDistricts[];
extern const size_t kDistrictCount;

struct LookupResult {
    size_t province_idx;
    size_t city_idx;
    size_t district_idx;
};

LookupResult FindDistrictById(const char* district_id);

const DistrictEntry* GetDistrict(size_t province_idx, size_t city_idx,
                                 size_t district_idx);

}  // namespace weather_cities
""",
        encoding="utf-8",
    )
    print(f"wrote {h.relative_to(REPO_ROOT)}")


def write_source(nested):
    provinces_sorted = sorted(nested.keys())

    flat_districts: list[tuple[str, str]] = []
    flat_cities: list[tuple[str, int, int]] = []
    province_ranges: list[tuple[str, int, int]] = []

    for prov in provinces_sorted:
        city_start = len(flat_cities)
        cities_sorted = sorted(nested[prov].keys())
        for city in cities_sorted:
            district_start = len(flat_districts)
            for district_name, district_id in nested[prov][city]:
                flat_districts.append((district_name, district_id))
            flat_cities.append(
                (city, district_start, len(nested[prov][city]))
            )
        province_ranges.append((prov, city_start, len(cities_sorted)))

    src = OUT_DIR / "weather_city_list.cc"
    lines: list[str] = [HEADER]
    lines.append('\n#include "weather_city_list.h"\n')
    lines.append("\n#include <string.h>\n")
    lines.append("\nnamespace weather_cities {\n")

    lines.append("\nconst DistrictEntry kDistricts[] = {\n")
    for name, district_id in flat_districts:
        lines.append(
            f"    {{ {cpp_string_literal(name)}, {cpp_string_literal(district_id)} }},\n"
        )
    lines.append("};\n")
    lines.append(
        "const size_t kDistrictCount = sizeof(kDistricts) / sizeof(kDistricts[0]);\n"
    )

    lines.append("\nconst CityEntry kCities[] = {\n")
    for name, district_start, district_count in flat_cities:
        lines.append(
            f"    {{ {cpp_string_literal(name)}, {district_start}, {district_count} }},\n"
        )
    lines.append("};\n")
    lines.append(
        "const size_t kCityCount = sizeof(kCities) / sizeof(kCities[0]);\n"
    )

    lines.append("\nconst ProvinceEntry kProvinces[] = {\n")
    for name, city_start, city_count in province_ranges:
        lines.append(
            f"    {{ {cpp_string_literal(name)}, {city_start}, {city_count} }},\n"
        )
    lines.append("};\n")
    lines.append(
        "const size_t kProvinceCount = sizeof(kProvinces) / sizeof(kProvinces[0]);\n"
    )

    lines.append(
        """
const DistrictEntry* GetDistrict(size_t province_idx, size_t city_idx,
                                 size_t district_idx) {
    if (province_idx >= kProvinceCount) {
        return nullptr;
    }
    const ProvinceEntry& pe = kProvinces[province_idx];
    if (city_idx >= pe.city_count) {
        return nullptr;
    }
    const CityEntry& ce = kCities[pe.city_start + city_idx];
    if (district_idx >= ce.district_count) {
        return nullptr;
    }
    return &kDistricts[ce.district_start + district_idx];
}

LookupResult FindDistrictById(const char* district_id) {
    LookupResult r{kProvinceCount, 0, 0};
    if (district_id == nullptr || *district_id == '\\0') {
        return r;
    }
    for (size_t p = 0; p < kProvinceCount; ++p) {
        const ProvinceEntry& pe = kProvinces[p];
        for (uint16_t c = 0; c < pe.city_count; ++c) {
            const CityEntry& ce = kCities[pe.city_start + c];
            for (uint16_t d = 0; d < ce.district_count; ++d) {
                const DistrictEntry& de = kDistricts[ce.district_start + d];
                if (strcmp(de.id, district_id) == 0) {
                    r.province_idx = p;
                    r.city_idx = c;
                    r.district_idx = d;
                    return r;
                }
            }
        }
    }
    return r;
}

}  // namespace weather_cities
"""
    )

    src.write_text("".join(lines), encoding="utf-8")
    print(
        f"wrote {src.relative_to(REPO_ROOT)} "
        f"({len(flat_districts)} districts, {len(flat_cities)} cities, "
        f"{len(province_ranges)} provinces, {src.stat().st_size / 1024:.1f} KB)"
    )


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        default = REPO_ROOT / "scripts" / "data" / "weather_district_id.csv"
        csv_path = default
    else:
        csv_path = Path(argv[1]).expanduser()
    if not csv_path.is_file():
        print(f"csv not found: {csv_path}", file=sys.stderr)
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    nested = parse_district_csv(csv_path)
    if not nested:
        print("no rows parsed -- check the input file format", file=sys.stderr)
        return 1
    write_header()
    write_source(nested)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
